# Generated by Django 3.2.4 on 2022-07-11 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('age_group', models.CharField(max_length=100, verbose_name='age_group')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.IntegerField()),
                ('therapist_id', models.IntegerField()),
                ('participant_id', models.IntegerField()),
                ('is_over', models.BooleanField(default=False, verbose_name='is_over')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.game')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
    ]
