# Generated by Django 3.2.4 on 2022-07-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participant_id',
            new_name='client_id',
        ),
    ]
