# Generated by Django 4.0.6 on 2022-07-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='quiz_questions',
        ),
    ]
