# Generated by Django 4.0.6 on 2022-07-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
