# Generated by Django 3.2.14 on 2022-08-08 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quizroom_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='quizroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizroom'),
        ),
        migrations.AlterField(
            model_name='quizroom',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
